version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_adatbazis
    environment:
      MYSQL_DATABASE: projekt_db
      MYSQL_ROOT_PASSWORD: titkosjelszo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_alkalmazas
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      # Itt bíráljuk felül az application.properties-t a Dockerből!
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/projekt_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: titkosjelszo
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: